// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl3hLSJyuU3E08oinQPMRX_s45BlK2_Ms',
    appId: '1:449349642727:web:cfefbbb62e54ccf7893542',
    messagingSenderId: '449349642727',
    projectId: 'fir-flutter-codelab-da6c7',
    authDomain: 'fir-flutter-codelab-da6c7.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-da6c7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAItqU6-QOBT3GSghGM7SQzIpvBbVSty4',
    appId: '1:449349642727:android:c915185dbb2382a0893542',
    messagingSenderId: '449349642727',
    projectId: 'fir-flutter-codelab-da6c7',
    storageBucket: 'fir-flutter-codelab-da6c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFjrdt7wPYL5hinHEwvbkWAgnHclq-RNQ',
    appId: '1:449349642727:ios:b60b5e730ebf9930893542',
    messagingSenderId: '449349642727',
    projectId: 'fir-flutter-codelab-da6c7',
    storageBucket: 'fir-flutter-codelab-da6c7.appspot.com',
    iosClientId: '449349642727-53d0dfru1gfibb7n2qnf4tbl2d6k842v.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFjrdt7wPYL5hinHEwvbkWAgnHclq-RNQ',
    appId: '1:449349642727:ios:b60b5e730ebf9930893542',
    messagingSenderId: '449349642727',
    projectId: 'fir-flutter-codelab-da6c7',
    storageBucket: 'fir-flutter-codelab-da6c7.appspot.com',
    iosClientId: '449349642727-53d0dfru1gfibb7n2qnf4tbl2d6k842v.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
